const charMap = {
  'E': 'empty', 'H': 'house', 'S': 'skyscraper', 
  'P': 'park', 'F': 'forest', 'W': 'water', 
  'R': 'road', 'I': 'industry'
};

const layouts = [
  // 1. Downtown Ring
  [
    "EEFFFFEEEEEFFEE",
    "EEERRRRRRRRREEE",
    "EERPEEEEEEEPREE",
    "EEREEEEEEEEEFEE",
    "EEREESSSSEEFREE",
    "EEREESIISEEFREE",
    "EERHHSSSIHHHREE",
    "RRRHHHHHHHHRRRR",
    "EERHHHHHHHHHREE",
    "EERHHPPPHHHHREE",
    "EEREEEEEEEEEREE",
    "EERPPEEEEEEEREE",
    "EEERRRRRRRRRREE",
    "EEEEEEEEEEEEEEE",
    "FFFFEEFEEEEFFFF"
  ],
  // 2. The River
  [
    "EHHREWWWREEFEEE",
    "EHHREWWWREEEFEE",
    "EEEPEWWWREEEEEE",
    "EHHREWWWREHHEEE",
    "RRRRRRWRRRRRRRR",
    "EHHREWWWRESHHEE",
    "EHPREWWWRESSPEE",
    "EEEREWWWRESSSRE",
    "EHHREWWWRESISRE",
    "RRRRRWWRRRRRRRR",
    "EEEREWWWREEIIRE",
    "EEEPEWWWREEEIRE",
    "EHEPEWWWREEEEEE",
    "EHHPEWWWREEEHEE",
    "EHHREWWWRRHHHEE"
  ],
  // 3. Industrial Edge
  [
    "WWWWWWWWWWWWWWW",
    "EEEEEEEEEERRREE",
    "EIIIIIEEEERRREE",
    "EIIIIIEEEERRREE",
    "EIIPIIEEEERRREE",
    "EEPEEEEEEEHHRRE",
    "RRRRRRRRRRHHRRE",
    "EEEEEEEEEEHHRRE",
    "EEFEEEEEEEHRRRE",
    "EFFFPEEEEEHRHHE",
    "EFFPEEEEEEHRHHE",
    "RRRRRRRRRRRRRRE",
    "EEFEEEEEEERRREE",
    "EEEEFEEEEERRREE",
    "EEFFFPEEEERRREE"
  ],
  // 4. Central Park
  [
    "EHHHHHREEEHHHHE",
    "RRRRRRRRRRRRRRE",
    "ESHREEEPREERHHE",
    "ESHREEPPPPERSSE",
    "ESHREPPPPPPRISE",
    "ESHREPPPPPPRISE",
    "RRRRRPPPPPRRRRR",
    "EEHREPPPPPPRIHE",
    "EEHREEPPPPERIHE",
    "EEHREEEPREERIHE",
    "EEHREEEEEEEPIHE",
    "EEHRRRRRRRRRRRE",
    "EEHEEHHREEIIIEE",
    "EEHEEHHREEIIIEE",
    "EEEEEEEPEEEEEEE"
  ],
  // 5. Gridlock
  [
    "SSRSRRSSRSSRSSR",
    "SSRSRRSSRSSRIIR",
    "SSRSRRSSRSSRIIW",
    "RRRRRRRRRRRRRRR",
    "SSRSRRSSRSSREER",
    "HHRSRRSSRSSREER",
    "HHRSRRSSRSSRPER",
    "RRRRRRRRRRRRRRR",
    "HHRSRRHHHSSRPER",
    "HHRSRRHSSSSRHER",
    "HHRSRRHSSSSRHER",
    "RRRRRRRRRRRRRRR",
    "EERPRRHHHSSRHER",
    "PPRPRRHHHSSREER",
    "EEPEPEEEEEEPEEE"
  ],
  // 6. Coastline
  [
    "HHEHHHHRRWWWWWW",
    "HPEHHHHRRWWWWWW",
    "HHEEPEERRWWWWWW",
    "HHEPEEERRWWWWWW",
    "RRRRRRRRRWWWWWW",
    "SSEEESSRRWWWWWW",
    "SSEESSSRREEWWWW",
    "SSESSSSRREEWWWW",
    "SSSSSSSREEEWWWW",
    "RRRRRRRREEEWWWW",
    "IIIEIIIRREEEWWW",
    "IIIIIIPRREEEWWW",
    "IIEIIIRRPPEEWWW",
    "IIIIIIIRREEEWWW",
    "IIIIIIIRRWWWWWW"
  ],
  // 7. Twin Hubs
  [
    "HHHHREEPPPEEREE",
    "HSSHRRRRRRRRREE",
    "HSHHREEEEEHEREE",
    "HSSHRREEEPEREEE",
    "HHHHRREEEEEEREE",
    "RRRRRREEEEERRRR",
    "EEPEEREEEEEREII",
    "EEPEEREEWWREEEI",
    "FFFEEEWWRRRRRII",
    "FFPEEWWRREEEEII",
    "EEEEWWRRREEEEEE",
    "EEEWWREESSRRRRR",
    "EWWWWRESSSSSEEH",
    "EWWWWRESSSSEEEH",
    "WWWEEERRRRRRRRR"
  ],
  // 8. Cross Highway
  [
    "EHHHHERREEFFFEE",
    "EHSSHERREEEPFEE",
    "EHSSHERREEEPPEE",
    "EHSHHERREEEPEEE",
    "EHHHHERREEEPEEE",
    "EEEEEERREEPPPEE",
    "RRRRRRRRRRRRRRR",
    "RRRRRRRRRRRRRRR",
    "EIIIIERREEESHHE",
    "EIIIIERREEESHHE",
    "EIIIEERREEESHHE",
    "EIIEEERREEESHHE",
    "EEEEWERREEEHHEE",
    "EWWWWERREEEHHEE",
    "EWWWWWRREEEHHEE"
  ],
  // 9. Sprawl
  [
    "HHHHHHHHREEHHHH",
    "HHPRPPHHRRRHHHH",
    "HHPPHHHHHREEEHH",
    "HRHHHHHHHREEEHH",
    "RRRRRRRRRREEEHH",
    "HHEEHHHHHRHHHHH",
    "HHPPHHHHHRHSSSH",
    "HHPHHHHHHRHSSHH",
    "HHHHHHHHHRRSHHH",
    "HHHHHHHRRRRRRRR",
    "RHHHHHHRHHHHHHH",
    "RHHHHHHRPHHHIIH",
    "RRRRRRRRPPPPIIH",
    "HHHHHHHRHIIIIIH",
    "HHHHHHHRHHIIIIH"
  ],
  // 10. The Diagonal
  [
    "EEEEEEREEEEEWWW",
    "EEEEEEREEEEEWWW",
    "EEPEEEREPEEEWWW",
    "EPRPEEREEEEWWWW",
    "PRRREERHHHHWWWW",
    "ERRREERHHHHHWWW",
    "RRRREERIIIIHHWW",
    "EEEERERIIIIIHHW",
    "PPERRERRRRRRRHW",
    "EEERRSSSEEEERRW",
    "PPERSSSSEEEERRR",
    "EEERSSSSSEEEERR",
    "EPERSSSSSEEEERE",
    "PPERSSSSSEEEEER",
    "RRRRRRRRRRRRRRR"
  ]
];

export const getRandomCityLayout = () => {
  const index = Math.floor(Math.random() * layouts.length);
  const layout = layouts[index];
  
  const grid = [];
  for (let r = 0; r < 15; r++) {
    const row = [];
    for (let c = 0; c < 15; c++) {
      const char = layout[r][c];
      row.push({ type: charMap[char] || 'empty' });
    }
    grid.push(row);
  }
  return grid;
};
